---
- name: Check if Kubernetes cluster is running
  ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info
  ignore_errors: true
  register: k8s_cluster_info
  changed_when: false

- name: Check result
  ansible.builtin.debug:
    msg: "Current user: {{ ansible_user }}. Kubernetes cluster is {{ 'running' if k8s_cluster_info.rc == 0 else 'not running' }}"
    # var: k8s_cluster_info



- name: Creating the Cluster
  when: k8s_cluster_info.rc != 0
  block:
    # - name: Fetch images
    #   ansible.builtin.command: kubeadm config images pull
    #   changed_when: true

    - name: Initialise the K8S cluster
      ansible.builtin.command:
        kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} --apiserver-advertise-address={{ apiserver_advertise_address }} --upload-certs
      register: kubeadm_init
      changed_when: true
      
    - name: Grant kubectl access to ubuntu user
      become_user: "{{ ansible_user }}"
      ansible.builtin.shell: |
        cd
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
        echo "alias k=kubectl" >> .bashrc
      changed_when: kubeadm_init.rc == 0
    
    - name: Check current user
      shell: |
        whoami
      register: current_user_output

    - name: Print current user
      debug:
        msg: "Current user: {{ current_user_output.stdout }}"

    - name: Create CNI folder
      become_user: "{{ ansible_user }}"  
      file:
        path: $HOME/kubernetes/manifests/CNI
        state: directory
        mode: '0755'

    - name: Download Calico manifest file
      become_user: "{{ ansible_user }}"  
      shell: curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml -O
      args:
        chdir: $HOME/kubernetes/manifests/CNI

    - name: Modify CALICO_IPV4POOL_CIDR in calico.yaml
      become_user: "{{ ansible_user }}"  
      replace:
        path: $HOME/kubernetes/manifests/CNI/calico.yaml
        regexp: '^# - name: CALICO_IPV4POOL_CIDR'
        replace: '- name: CALICO_IPV4POOL_CIDR'

    - name: Set value of CALICO_IPV4POOL_CIDR in calico.yaml
      become_user: "{{ ansible_user }}"  
      replace:
        path: $HOME/kubernetes/manifests/CNI/calico.yaml
        regexp: '^#   value: "192\.168\.0\.0\/16"'
        replace: '  value: "{{ k8s_pod_network_cidr }}"'

    - name: Apply Calico manifest file
      become_user: "{{ ansible_user }}"  
      shell: kubectl apply -f calico.yaml
      args:
        chdir: $HOME/kubernetes/manifests/CNI

# ====== Create K8S Cluster Joining script ==========
- name: Create cluster joining script
  ansible.builtin.shell: |
    kubeadm token create --print-join-command > /tmp/join_cluster.sh
    chmod a+x /tmp/join_cluster.sh
  changed_when: true

- name: Fetch cluster joining script
  ansible.builtin.fetch:
    src: /tmp/join_cluster.sh
    dest: join_cluster.sh
    flat: true

#     - name: Install CNI
#       ansible.builtin.shell: |
#         kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
#         sleep 30
#       changed_when: kubeadm_init.rc == 0

