name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Send event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.actor}}/${{var.REPO_CICD}}/dispatches \
            -d '{"event_type":"dispatch-event", "client_payload" : {"environment": "dev" }}'

